ardoq/rxbeach

src/actionCreator.tests.ts, src/actionCreator.ts, src/index.ts, src/internal/index.ts, src/internal/testUtils.ts, src/internal/types.ts, src/namespace.tests.ts, src/namespace.ts, src/types/Action.ts
Makes the `type`, `meta`, `meta.namespace` and `payload` fields of
action objects and action creators protected by TypeScript's `readonly`
keyword and by using `Object.freeze` on the action objects and action
creators when they are created.
This is basically a lite version of #25, which at least moves us closer to fixing #21.
=> Freeze actions and action creators

README.md
"early ages of x" would refer to an epoch, like "early ages of mankind"
"early stages of x" is a more common expression which fits this context better.
https://www.google.com/search?q=%22early+ages+of%22
https://www.google.com/search?q=%22early+stages+of%22
=> improve grammar

.gitignore, .nycrc, ava.config.js, examples/actions.spec.ts, examples/namespacingActionCreators.spec.ts, examples/namespacingActionDispatchers.spec.ts, package.json, src/actionCreator.spec.ts, src/namespace.spec.ts, src/operators/operators.spec.ts, yarn.lock
This is related to #23 . I integrated Ava into the project, and converted all existing tests to it. The new tests use the `*.spec.ts` extension. I also kept the old tests for now.
I also set up coverage reporting using `nyc`.
This PR (for now) doesn't cover [browser testing](https://github.com/avajs/ava/blob/master/docs/recipes/puppeteer.md) or [React testing](https://github.com/avajs/ava/blob/master/docs/recipes/react.md), but they are both supported by Ava.
You can run the tests using `yarn test-ava`. Don't forget to run `yarn install` beforehand.
For me, it takes about 10.5 seconds with the coverage report, and around 8.5 seconds if I just run `ava`. From some initial research, it seems that the slowness could be coming from a sub-optimal globbing pattern used in the configuration, or …
=> Switch to ava test framework

examples/globalActions.ts, examples/namespacingActionCreators.spec.ts, examples/namespacingActionDispatchers.spec.ts, examples/routines.spec.ts, src/internal/index.ts, src/internal/types.ts, src/namespace.spec.ts, src/operators/operators.ts, src/routines.ts, src/types/helpers.ts
RxBeach is TypeScript first, and should be strictly typed where
possible. AnyAction has been removed in favour of UnknownAction.
Where AnyAction in practice had `payload?: any` as a field,
UnknownAction has `payload?: unknown`.
Other uses of any in the codebase has also been reviewed - and have
found to only relate to
- Error subject
- Implementations
- Tests
=> Remove AnyAction

.eslintrc.js, package.json, src/internal/types.tspec.ts, src/types/Action.tspec.ts, src/types/ActionCreator.tspec.ts, src/types/helpers.tspec.ts, yarn.lock
@davidnegley uncovered some strange behaviour in regards to action creators of union types. 
This PR explores ways in which we can test the type definitions.
While developing I found a fundamental limitation in our current `Action` type: **It does not support any union types** - this includes disjunct types (`A | B`), booleans and enums.
A current workaround is to wrap the payload in an object.
=> Test types

.eslintrc.js, src/actionCreator.spec.ts, src/actionCreator.ts, src/actionCreator.tspec.ts
These overloads allows TypeScript to properly infer Payloads for union payload
types.
Fixes #34.
=> Add void and payload overloads for actionCreator

src/operators/index.ts, src/operators/operators.spec.ts, src/operators/operators.ts
An operator to carry the initial payload through a new operator and returns it combined as an array with results from the operator.
```ts
action$.pipe(
extractPayload(),
carry(map(payload => payload.foo))
tap(([payload, foo]) => {
// `payload.foo === foo` equals `true`
})
)
```
Big help from Tobias 🐧
=> Add carry operator

src/operators/index.ts, src/operators/operators.spec.ts, src/operators/operators.ts
The apply operator allows us to carry some context to multiple operators
at once. In most cases, `carry` would be preferred, but we have not
found any other way to provide context to `catchError`.
Closes #59
=> Add apply operator

src/internal/CombinationOperator.ts, src/internal/index.ts, src/internal/markers.spec.ts, src/internal/markers.ts, src/operators/derivedStream.spec.ts, src/operators/derivedStream.ts, src/operators/index.ts, src/operators/operators.spec.ts, src/operators/operators.ts, src/operators/withStreams.spec.ts, src/operators/withStreams.ts
This PR adds the tools we need to analyze how streams depend on each other.
The building blocks of this is as follows:
- `Marker` - A simple object which says something about how a stream is built up. The markers actually represent a stream as a tree in itself. They tell us:
- The name of the stream
- The sources of the stream (streams which updates leads to this stream updating)
- The dependencies of the stream (streams which we retrieve data from)
- `MarkerOperator` - A no-op operator that places a marker on a stream
- `findMarker` - A function which recursively looks at the operators and sources for a stream to find the closest marker
Have a look at the test for `derivedStream` to see how the structure might look.
=> Stream dependency analysis

src/internal/index.ts, src/internal/markers.ts, src/operators/decorated.ts
Previously all markers would add an extra function call for each emitted
value in an observable. This was because the markers where added by
using `Observable.lift`, which leaves it to the operator to handle
emitted values.
This new implementation just extends Observable with the marker field,
and lets the Observable implementation handle subscribing to the source.
This means we don't add any extra function calls for the emitted values
to pass through.
As a side note - notice how we didn't need to change a single test, and they are all still passing with 100% line coverage.
=> Remove runtime overhead of markers

examples/reducers.spec.ts, src/index.ts, src/reducer.spec.ts, src/reducer.ts
This commit makes the reducer constructor (`reducer`) return a function
that can be called like a plain reducer function. This allows for easier
composition of reducers.
BREAKING CHANGE: `ReducerEntry` has been renamed to `RegisteredReducer`,
and changed shape from an array to a function with a `trigger` property.
=> feat: Reducer constructor returns a reducer function

src/reducer.spec.ts, src/reducer.ts
When an error is caught, it is emitted to an optional error subject,
while the stream itself does not emit. This means that any subscribers
will still have the previously emitted value.
--- 
While implementing #99, I found that it is practically impossible to implement error handling at another level if we wish to keep the original stream alive, so I suggest that we add error handling to combineReducers.
[Some useful reading about RxJS error handling confirms that:](https://iamturns.com/continue-rxjs-streams-when-errors-occur/)
> If an error is thrown within an operator, the stream will always complete.
This means that the only way we can avoid an error at a later level is by using `switchMap`, but this is not really desirable with `combineReducers`:
```typescript
export const …
```
=> feat(reducers): combineReducers catches errors when reducing values

src/reduceState.spec.ts, src/reduceState.ts, src/reducer.spec.ts
The pattern for creating state streams is one of the few missing pieces in ardoq-front to fully make use of reducers from rxbeach, so I thought I would give this a go.
The goal is for this to replace `createReducedStateStream` in ardoq-front (and hopefully most cases of `createStateStream` now that we have data reducers).
**reduceState guarantees that:**
- a value is emitted upon subscription with startWith (state streams can't be lazy)
- the stream producer is shared, if there are multiple subscriptions
the reducers will only run once
- the state stream producer lives on "forever" throughout the app lifecycle,
subsequent subscriptions will always get the previous state calculation
even though there are no subscribers (i.e. the stream is not refcounted)
**WIP:**
- a state stream forwards …
=> ARD-4020 Implemented state stream tooling with tests (WIP)

src/derivedStream.ts, src/internal/routineFunc.ts
alphabet practice
trying to address this @ts-ignore https://github.com/ardoq/ardoq-front/blob/master/src/js/ardoq/streams/assets/assets$.ts#L249 for a call to `derivedStream` which just recently increased the number of streams passed to 10.
=> ARD-3813 add 10 stream parameter overload

package.json, yarn.lock
I want to try this for a while. We might find it too aggressive, or we might end up loving it :)
I'm most concerned about losing long commit messages because of silly mistakes. Say I write a paragraph explaining my changes, and then `commitlint` rejects the commit message because the header had a capital letter in the commit subject.
```
chore(internal): lint commit messages on commit
```
- The header may begin with a `fixup!`
- After `fixup!` there must be a type. One of: 'build', 'ci', 'chore', 'docs', 'feat', 'fix', 'perf', 'refactor', 'revert', 'style', 'test'
- After the type there may be a scope. It must be all lower case, but may contain spaces, dashes or underscores
- The subject itself cannot have a capital first letter
Over time I think it will come naturally what scopes to use. …
=> chore: lint commit messages on commit

src/operators/reduceState.spec.ts, src/operators/reduceState.ts
Debouncing state streams made it unsafe to use withLatestFrom,
since the stream calculations were debounced.
For now, reverted to emitting all state calculations.
=> fix(reducers): removed debouncing from reduceState

package.json, src/react/connect.spec.ts, src/react/connect.ts, yarn.lock
A higher order component for connecting react components to streams.
Builds upon the `useStream` hook, and is intended for use in class based components that can't use the hook themselves.
Rigid testing with `react-test-renderer`, which renders the components without a DOM. Have also chosen to not write any `tsx`, so we won't have to deal with more tooling.
=> feat(react): add connect React HOC

src/index.ts, src/persistentReducedStream.spec.ts, src/persistentReducedStream.ts
This PR investigates how we can do the final level of tooling for creating reduced state streams.
A reduced state stream is a stream built up of reducers (action- and stream reducers) that contains global application state. They should have only one instance each and never reset their state.
As the state is never reset, i.e. it is independent of subscriptions, it can also be exposed through a property on the stream. This gives us a nice interface between the stream and sync worlds, and could make `withLatestFrom` unnecessary in many cases (Though that might not be something we want to do). 
The current implementation in this PR extends `BehaviorSubject` and subscribes the stream when created. This is not ideal, as `next`, `error` and `complete` are available as methods on the objects, …
=> Reduced State Stream Tooling

src/internal/performance/performanceMeasurements.ts, src/operators/reduceState.ts, src/persistentReducedStream.ts, src/reducer.spec.ts, src/reducer.ts
If the window.performance API is available and a marker name is passed to
combineReducers it will add performance markers using the window.performance API.
The markers and measurements can be read and logged by interacting with
the performance API.
---
The benefit of using the window performance API is that they're available when using the browser for performance profiling:
I first tried to implement this in a way that performance measurements would also work when window isn't available by falling back to using the node performance API, but it wasn't straight forward. Since we don't have a use-case for that yet I think this is fine.
=> feat(reducers): added performance measurements to combineReducers

yarn.lock
https://ardoqcom.atlassian.net/browse/ARD-5317
I got there by:
- adding `"mkdirp": "0.5.4"` to `package.json`
- running `yarn install`
- manually replacing the `mkdirp` version from `0.5.1` to `0.5.4` in `yarn.lock`
- removing `"mkdirp": "0.5.4"` from `package.json`
- running `yarn install`
=> fix: upgraded vulnerable dependency

yarn.lock
Updates a lot of transitive dependencies and fixes most of the security
warnings.
Lockfile generated by `yarn upgrade`, which updates all our transitive dependencies it seems.
Before this, `yarn audit` reported 21 vulnerabilities. It now only reports 4.
=> chore(deps): generate new yarn lockfile

src/internal/testing/mock.ts, src/persistentReducedStateStream.ts, src/persistentReducedStream.spec.ts, src/persistentReducedStream.ts
Adds rudimentary namespace support to persistentReducedStreams. 
Review commit by commit, and take a look at the commit messages.
=> Support namespace in persistentReducedStreams

src/operators/index.ts, src/operators/operators.spec.ts, src/operators/operators.ts
This is a generalization of two utils I introduced in ardoq-front#7592
https://github.com/ardoq/ardoq-front/pull/7592/files#diff-5ef729189ec41118a686b2dec008e045R61-R69
I think it makes sense to introduce this as a single operator, though the behaviour actually changes between the 1-arg and 0-arg version. I think the name will still flow very naturally in both cases, though.
=> feat: add withoutNamespace operator

src/persistentReducedStateStream.ts, src/persistentReducedStream.spec.ts, src/reducer.spec.ts, src/reducer.ts
The motivation for this change is to allow more reducers to be statically created. See [this example](https://github.com/ardoq/ardoq-front/blob/master/src/js/ardoq/search/QueryEditor/queryEditor%24.ts#L195-L212) from ardoq-front.
As you can see from the tests. The syntax is not ideal for void actions (with the underscores/unused arguments).
=> feat: forward namespaces to reducers

src/reducer.ts
This gives nicer error messages that will more often match the actual problem the user has,
though there is still a high chance that TypeScript will show the "wrong" error.
The old order was:
1. single action with payload
2. single action without payload
3. multiple actions with overlapping payload
4. multiple actions without overlapping payloads
5. multiple actions without payloads
6. stream
The new order is:
1. stream
2. multiple actions with overlapping payload
3. multiple actions without overlapping payloads
4. multiple actions without payloads
5. single action with payload
6. single action without payload
It's important to remember that TypeScript will choose the first overload which doesn't give an error for the function call, or display the error of the last overload. However, …
=> fix: order reducer overload from most to least complex

.gitignore, src/operators/operators.spec.ts, src/operators/operators.ts
The carry operator had a bug that caused it to subscribe twice to the routines where it was used. More detailed description. 
TLDR: caused by difference between hot vs cold observables
=> fix: ARD-9960 fixed carry bug

docs/qualified-action-names.md, src/actionCreator.spec.ts, src/actionCreator.ts, src/actionCreator.tspec.ts, src/operators/operators.spec.ts, src/operators/operators.tspec.ts
BREAKING CHANGE: This ensures every action has name of the form
`[qualifier] action name`.
As discussed in the [frontend meeting on 11.08.2021](https://docs.google.com/document/d/1mmmSX7hUaa5buSyYi54OyTKGTm2__S1lUgKt3Dpa_rA/edit#heading=h.3ezqzkurn626).
ARD-9728
~~Seems to work quite well, but it will be some work to actually change the names in ardoq-front.~~ Already done in ardoq/ardoq-front#9808
CC: @davidnegley @jsloat @OyvindSabo @oyvinmar
=> feat: enforce qualifier in action names

src/react/index.ts
It's all in place, just the hook was not exposed from the package, so it cannot be used.
=> chore: expose useStream hook

src/react/connect.spec.ts, src/react/connect.ts, src/react/index.ts
The new `connectInstance` function works the same as `connect`, but
takes a function that takes an instance name and produces
`ObservableInput`. This is well suited for namespaced streams.
=> feat(react): add `connectInstance` function
